if(NOT DEFINED SOURCE_CONFIG OR NOT DEFINED DEST_CONFIG)
    message(FATAL_ERROR "SOURCE_CONFIG and DEST_CONFIG are required.")
endif()

if(NOT EXISTS "${DEST_CONFIG}")
    file(COPY_FILE "${SOURCE_CONFIG}" "${DEST_CONFIG}")
endif()
